services:
  postgres:
    image: postgres:latest
    container_name: todo-postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    networks:
      - pgnetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: todo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@gmail.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - "8080:80"
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge

volumes:
  postgres_data: