# Generated by Django 5.0.6 on 2024-06-16 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
